apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: <your-image>
        ports:
        - containerPort: 3000
        env:
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: REDIS_HOST
          value: redis-service
        - name: AWS_REGION
          value: us-east-1
